options:
  logging: 'NONE'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sturdy-filament-400423/assignment1-frontend', './frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sturdy-filament-400423/assignment1-frontend']

images:
- 'gcr.io/sturdy-filament-400423/assignment1-frontend'
