#Here is the update to trigger the pipeline
options:
  logging: 'CLOUD_LOGGING_ONLY'
  env:
    - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'
    - 'CLOUDSDK_CONTAINER_ZONE=us-central1-a'
    - 'CLOUDSDK_CORE_PROJECT=sturdy-filament-400423'
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'

substitutions:
  _BUILD_ID: "$BUILD_ID"  # Use the predefined Cloud Build ID

steps:
# Build the frontend Docker image and tag with BUILD_ID
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sturdy-filament-400423/assignment1-frontend:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sturdy-filament-400423/assignment1-frontend:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/frontend-deployment', 'frontend=gcr.io/sturdy-filament-400423/assignment1-frontend:$SHORT_SHA', '--namespace=frontend']

images:
  - 'gcr.io/sturdy-filament-400423/assignment1-frontend:$SHORT_SHA'
