options:
  logging: 'CLOUD_LOGGING_ONLY'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/sturdy-filament-400423/assignment1-frontend', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/sturdy-filament-400423/assignment1-frontend']

images:
- 'us.gcr.io/sturdy-filament-400423/assignment1-frontend'
